In [26]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as  sns
import re

---
## **Load  Dataset**

In [14]:
df=pd.read_csv('D:\\Github\\PRODIGY_DS_04\\data\\twitter_training.csv')
df.columns = ['id', 'topic', 'sentiment', 'text']
df.head()

,id,topic,sentiment,text
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...

---
## **Data Understanding**

In [ ]:
df.shape,df.info(),df.describe(),df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74681 entries, 0 to 74680
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         74681 non-null  int64
 1   topic      74681 non-null  object
 2   sentiment  74681 non-null  object
 3   text       73995 non-null  object
dtypes: int64(1), object(3)
memory usage: 2.3+ MB

((74681, 4),
 None,
                  id
 count  74681.000000
 mean    6432.640149
 std     3740.423819
 min        1.000000
 25%     3195.000000
 50%     6422.000000
 75%     9601.000000
 max    13200.000000)

In [11]:
df.select_dtypes(include='number').columns.to_list()

['id']

In [12]:
df.select_dtypes(include='object').columns.to_list()

['topic', 'sentiment', 'text']

In [21]:
df.sample(10,random_state=42)

,id,topic,sentiment,text
54877,2224,CallOfDuty,Negative,What nonsense!
15760,3096,Dota2,Irrelevant,me am egg man dota no i hate robbie - Casey
2999,1720,CallOfDutyBlackopsColdWar,Negative,Still iffy about this
3251,1765,CallOfDutyBlackopsColdWar,Positive,sooo hyped for this. Love the way Call of Duty...
54480,2158,CallOfDuty,Negative,GET SHIT ON NERDS!
59873,3462,Facebook,Neutral,I will back later cause know i am so upset and...
59768,3444,Facebook,Positive,I know social movements Nice Vintage Rad 4 shi...
34601,6744,Fortnite,Irrelevant,I FINALLY MADE 100 SUBSCRIBERS THANK YOU GUYS....
7173,9233,Overwatch,Positive,What Thanks y'all!.
15126,2990,Dota2,Positive,Dota 2 after 6 months let's pretend goo

In [ ]:
df[df['text'].str.strip()==''].sum()

id           0
topic        0
sentiment    0
text         0
dtype: object

In [ ]:

df['text'].str.contains('http').sum()
df['text'].apply(lambda x: bool(re.search(r'http\S+', str(x)))).sum()

2449

In [29]:
df['text'].str.contains('@').sum()

18215

In [30]:
df['text'].str.contains('#').sum()

35

In [31]:
df['text'].apply(lambda x: any(char in str(x) for char in ['😀','😂','🔥','❤️'])).sum()

np.int64(0)

In [32]:
df['text'].apply(lambda x: bool(re.search(r'[^a-zA-Z0-9\s]', str(x)))).sum()

np.int64(63083)

In [ ]:
df['text_length'] = df['text'].apply(lambda x: len(str(x).split()))
df[df['text_length'] < 3]

---
## **Data Cleaning**

In [38]:
df.isna().sum()
df=df.dropna(subset=['text'])
df.isna().sum()

id             0
topic          0
sentiment      0
text           0
text_length    0
dtype: int64

In [20]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [ ]:
df=df[df['text'].str.strip()!='']
df[df['text'].str.strip()==''].sum()

In [ ]:
df=df[df['text_length'] >= 3]

In [ ]:
df['text']=df['text'].str.lower()

0        i am coming to the borders and i will kill you...
1        im getting on borderlands and i will kill you ...
2        im coming on borderlands and i will murder you...
3        im getting on borderlands 2 and i will murder ...
4        im getting into borderlands and i can murder y...
                               ...
74676    just realized that the windows partition of my...
74677    just realized that my mac window partition is ...
74678    just realized the windows partition of my mac ...
74679    just realized between the windows partition of...
74680    just like the windows partition of my mac is l...
Name: text, Length: 67877, dtype: object